from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID

from stratiq.domain.entities import (
    ChatMessage,
    ChatSession,
    Chunk,
    Citation,
    DecisionCard,
    Document,
    ExecutiveReport,
    KPI,
    User,
)


class UserRepository(Protocol):
    async def create(self, email: str, password_hash: str, full_name: str) -> User: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...


class DocumentRepository(Protocol):
    async def create(self, document: Document) -> Document: ...
    async def get(self, document_id: UUID, owner_id: UUID) -> Document | None: ...
    async def list_for_owner(self, owner_id: UUID) -> list[Document]: ...
    async def update(self, document: Document) -> Document: ...
    async def get_by_id(self, document_id: UUID) -> Document | None: ...


class ChunkRepository(Protocol):
    async def replace_for_document(self, document_id: UUID, chunks: list[Chunk]) -> list[Chunk]: ...
    async def list_for_document(self, document_id: UUID) -> list[Chunk]: ...
    async def get_many(self, chunk_ids: list[UUID]) -> list[Chunk]: ...


class KPIRepository(Protocol):
    async def replace_for_document(self, document_id: UUID, kpis: list[KPI]) -> list[KPI]: ...
    async def list_for_owner(self, owner_id: UUID, document_id: UUID | None = None) -> list[KPI]: ...
    async def get(self, kpi_id: UUID, owner_id: UUID) -> KPI | None: ...


class DecisionRepository(Protocol):
    async def replace_cards(
        self,
        owner_id: UUID,
        cards: list[DecisionCard],
        document_id: UUID | None = None,
    ) -> list[DecisionCard]: ...
    async def list_cards(
        self, owner_id: UUID, document_id: UUID | None = None
    ) -> list[DecisionCard]: ...
    async def get_card(self, card_id: UUID, owner_id: UUID) -> DecisionCard | None: ...
    async def save_executive_report(self, report: ExecutiveReport) -> ExecutiveReport: ...
    async def get_latest_executive_report(
        self, owner_id: UUID, document_id: UUID | None = None
    ) -> ExecutiveReport | None: ...


class ChatRepository(Protocol):
    async def create_session(self, owner_id: UUID, title: str) -> ChatSession: ...
    async def get_session(self, session_id: UUID, owner_id: UUID) -> ChatSession | None: ...
    async def list_sessions(self, owner_id: UUID) -> list[ChatSession]: ...
    async def add_message(
        self,
        session_id: UUID,
        role: str,
        content: str,
        citations: list[Citation] | None = None,
    ) -> ChatMessage: ...
    async def list_messages(self, session_id: UUID, owner_id: UUID) -> list[ChatMessage]: ...


class AuditRepository(Protocol):
    async def record(
        self,
        action: str,
        actor_id: UUID | None,
        resource_type: str | None = None,
        resource_id: str | None = None,
        details: dict[str, Any] | None = None,
    ) -> None: ...


class ObjectStorage(Protocol):
    async def put(self, key: str, data: bytes, content_type: str) -> str: ...
    async def get(self, key: str) -> bytes: ...
    async def delete(self, key: str) -> None: ...


class TokenStore(Protocol):
    async def store_refresh(self, user_id: UUID, token_id: str, ttl_seconds: int) -> None: ...
    async def revoke_refresh(self, user_id: UUID, token_id: str) -> None: ...
    async def is_refresh_valid(self, user_id: UUID, token_id: str) -> bool: ...
    async def blacklist_access(self, jti: str, ttl_seconds: int) -> None: ...
    async def is_access_blacklisted(self, jti: str) -> bool: ...


class JobQueue(Protocol):
    async def enqueue_process_document(self, document_id: str) -> str: ...


class EmbeddingsPort(Protocol):
    async def embed(self, texts: list[str]) -> list[list[float]]: ...


class LLMPort(Protocol):
    async def complete_json(self, system: str, user: str) -> dict[str, Any]: ...
    async def complete_text(self, system: str, user: str) -> str: ...


class VectorStore(Protocol):
    async def ensure_collection(self, vector_size: int) -> None: ...
    async def upsert_chunks(
        self,
        points: list[dict[str, Any]],
    ) -> None: ...
    async def search(
        self,
        vector: list[float],
        owner_id: str,
        top_k: int,
        document_id: str | None = None,
    ) -> list[dict[str, Any]]: ...
    async def delete_document(self, document_id: str) -> None: ...


class DocumentParser(Protocol):
    def supports(self, filename: str, content_type: str) -> bool: ...
    def parse(self, data: bytes, filename: str) -> str: ...
